### ISSUE TITLE
How to soft remove for relation of collections?

### ISSUE THREAD

**Issue by thearabbit** [zimme/meteor-collection-softremovable#11]
For example I have 3 collections (relations)
```js
address (_id, name)
customer (_id, name, gender, addressId)
order (_id, date, customerId)
```
When I soft remove on `address`, so the `customer` and `order` too.
And restore too.

**Comment by zimme** [comment]
Maybe use a method and first soft remove address, then the customer and then the order?

I don't really have support for relation ships, I'll look into adding support for before and after soft remove hook into the @matb33's collection-hooks system if I get the time.

You could probably setup after update hooks which checks if $set: {removed: true}/$unset: {removed: true} is present and do what you want in those cases.

**Comment by thearabbit** [comment]
Look great if have own hook such before /update soft remove and restore.
Waiting ....

**Comment by zimme** [comment]
I'll close this and I've opened a new issue for tracking the potential new feature. #12

**Comment by thearabbit** [comment]
Please explain how to check `$set: {removed: true}/$unset: {removed: true}`.
```js
if(modifier.$set.removed === true){
}

if(modifier.$unset.removed === true){
}
```
Correct or not???

**Comment by zimme** [comment]
Something like this in an after update hook should hopefully work.
```js
if (modifier && modifier.$set && modifier.$set.removed) {
  Do stuff if if the update is soft removing a document
}

if (modifier && modifier.$unset && modifier.$unset.removed) {
  Do stuff if the update is restoring a document
}
```

**Comment by thearabbit** [comment]
Thank again, but I don't understand for the checking with order (why not use only `modifier.$set.removed`).

**Comment by zimme** [comment]
You can probably remove the `modifier` from the checks because the `modifier` should always be set, but the `$set` and `$unset` might not be set so we need to check that they are set before checking if the `removed` is available otherwise you will get an error about not being able to access `removed` of `undefined`.
