### ISSUE TITLE
Don't modify object given to .find

### ISSUE THREAD

**Issue by lorensr** [zimme/meteor-collection-softremovable#16]
This:

```coffeescript
item = 
  foo: 0

unless Items.findOne item
  console.log item
  Items.insert item
```

gives:
```
{ foo: 0,
  removed: { '$exists': false }}
Error: key $exists must not start with '$'
```

It's fixed by `Items.findOne _.clone item`, but it would be better if that wasn't necessary.

**Comment by zimme** [comment]
Nice catch, should be able to work on a cloned object in the before find hook to fix this

**Comment by lorensr** [comment]
Confirmed fixed in rc.1

**Comment by zimme** [comment]
`1.0.5` published.
