### ISSUE TITLE
$unset' is empty. You must specify a field like so...

### ISSUE THREAD

**Issue by roelvan** [zimme/meteor-collection-softremovable#2]
This error only happens on my production server (mongo v.2.6.7). Locally it works fine (v.2.4.12)
```
Exception while invoking method 'markAsPaid' MongoError: '$unset' is empty. You must specify a field like so: {$mod: {<field>: ...}}
```

**Comment by zimme** [comment]
The method `markAsPaid`, which function is it using? `softRemove`, `restore`, `find`, `findOne`, or `update`?

**Comment by roelvan** [comment]
it's an `update` function that changes a `paid` field from `false` to
`true`.

**Comment by roelvan** [comment]
it's an `update` function that changes a `paid` field from `false` to
`true`.

**Comment by zimme** [comment]
Are you using autoform/simple-schema/collection2?

**Comment by zimme** [comment]
Ok, after a bit of research this is related to a change from 2.4 -> 2.5/2.6 where it's not longer acceptable to provide an empty modifier for an update when using $set/$unset.

I'll take a look at removing empty $set/$unset modifiers before returning them.

**Comment by zimme** [comment]
I don't have mongo 2.5/2.6 available.

Tested the changes with the bundled mongo version and no regression with this fix.

Could you please test 1.0.3-rc.1 on your production server to see if the fix works?

**Comment by roelvan** [comment]
Yep that did the trick on my production server. Works like a charm now.
Yes, I am also using `autoform/simple-schema/collection2`
