### ISSUE TITLE
Add config flag for isSelectorId

### ISSUE THREAD

**Issue by chmac** [zimme/meteor-collection-softremovable#24]
Firstly, thanks for both this package and the underlying collection-behaviours package. Great contributions to the meteor community.

I just added the package, deleted a document, went to the document route, and I still see the document. WTF?

After digging into the code, I see that if I find a document by ID, then the `removed` value is ignored. That seems totally counter intuitive to me, and I didn't get that from reading the docs. I'd suggest that at the very least it's a configurable behaviour, or that it defaults to the other way round.

Of course, having released a version that behaves this way, I guess other folks rely on this behaviour, so it should probably remain, at least until a breaking change release.

**Comment by zimme** [comment]
My plan is to actually do a rewrite of all my behaviour packages in es2015,
make this package work as you would expect, add hooks for this package, and
also make remove be soft remove and add hardRemove as the current remove
function.

**Comment by chmac** [comment]
Defaulting the `.remove()` method to `softRemove()` and adding `.hardRemove()` would be great. :+1:

If you're considering the switch from coffee to ES6 you might find [this](http://tech.noredink.com/post/111583727108/dont-replace-coffeescript-with-es6-transpilers) interesting. I like coffee and it's the most reasoned argument I've heard about the varying merits of the two. It certainly put down the "ES6 is the new coffee" argument for me. The biggest reason I hear for switching to ES6 is that it's what all the cool kids are doing...

**Comment by zimme** [comment]
> Defaulting the .remove() method to softRemove() and adding .hardRemove() would be great.

Yeah I thought so too. :sunglasses:

> The biggest reason I hear for switching to ES6 is that it's what all the cool kids are doing... :-)

My biggest reason is that it will open up for more PR's as a lot of people are more comfortable
with javascript than with coffeescript. I don't feel like I've had many PR's for my packages and I
don't think it is because I write perfect code :stuck_out_tongue_closed_eyes:

**Comment by chmac** [comment]
Yeah, that might be the strongest reason I've heard to think about changing. I took a lot of inspiration from GitHub's style guide saying "Write new JS in CoffeeScript". But that has disappeared now, so maybe times are a changing... :-)

Happy to close this issue pending the rewrite...

**Comment by zimme** [comment]
also I'm thinking about moving my behaviour packages into `behaviour:core`, `behaviour:softremove`, `behaviour:timestamp` etc.
