### ISSUE TITLE
Does not work with publishComposite

### ISSUE THREAD

**Issue by roelvan** [zimme/meteor-collection-softremovable#25]
still publishes the soft removed docs inside a publishComposite call.

https://github.com/englue/meteor-publish-composite

**Comment by zimme** [comment]
Had a quick look at his package and nothing in his code scream at me that he's overriding the `find` calls or anything.

Are you sure you're not doing some multiple finds where one of those might be returning removed documents?

I'll look into this more closely once I'm done with the re-write. I'm almost done with `collection-behaviours` and after that `timestampable` is next and this after that.

**Comment by roelvan** [comment]
I did a normal find without the "removed: true” setting. I’ll take a deeper
look at it, maybe the problem is somewhere else. I’ll let you know soon as
I know more. Thanks for your effort!

On Fri, Dec 11, 2015 at 3:40 PM Simon Fridlund <notifications@github.com>
wrote:

> Had a quick look at his package and nothing in his code scream at me that
> he's overriding the find calls or anything.
>
> Are you sure you're not doing some multiple finds where one of those might
> be returning removed documents?
>
> I'll look into this more closely once I'm done with the re-write. I'm
> almost done with collection-behaviours and after that timestampable is
> next and this after that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zimme/meteor-collection-softremovable/issues/25#issuecomment-163875726>
> .
>
-- 
Met vriendelijke groeten,

Roel Vaneyghen
+32 484 49 08 15

Co-founder of
www.klikkid.be | www.pixelfreaks.io | www.trouweninbeeld.be | www.lost.io |
www.ralphstarck.com

**Comment by roelvan** [comment]
I just tested some extra scenarios and it has nothing to do with the publishComposite package. I have the exact same behaviour in a normal publish.

This what I get when I alter my publication:

Doesn't publish the softRemoved docs: **good**
```
Meteor.publishComposite 'singleBooking', (bookingId) ->
  check bookingId, String
  {
    find: -> Bookings.find()
    children: [
      {
        find: (booking) -> Events.find _id: booking.eventId
      }
      {
        find: (booking) ->
          if booking.referrerId?
            Bookings.find {_id: booking.referrerId},
              fields:
                _id: 1
                fullName: 1
      }
    ]
  }
```

Does publish the softRemoved docs: **bad**

```
Meteor.publishComposite 'singleBooking', (bookingId) ->
  check bookingId, String
  {
    find: -> Bookings.find _id: bookingId
    children: [
      {
        find: (booking) -> Events.find _id: booking.eventId
      }
      {
        find: (booking) ->
          if booking.referrerId?
            Bookings.find {_id: booking.referrerId},
              fields:
                _id: 1
                fullName: 1
      }
    ]
  }
```

This is what I changed:
From `find: -> Bookings.find()` to `find: -> Bookings.find _id: bookingId`

Not sure if that is helpful?

**Comment by zimme** [comment]
So you're finding by `_id`, that will find even soft removed documents.

**Comment by zimme** [comment]
This behaviour will change with the next version, because this is resulting in unexpected behaviour client-side, which I thought would be a convenience at the time I wrote this.

**Comment by roelvan** [comment]
In that case I will add: `removed: {$ne: true}` explicitly and change it once the new version is out. Thanks for your time.
