### ISSUE TITLE
minimongo dangerous selector protection check failed

### ISSUE THREAD

**Issue by WayneUong** [zimme/meteor-collection-softremovable#26]
Please look at this issue: https://github.com/meteor/meteor/issues/8220

**Comment by zimme** [comment]
I'll look into it this weekend and try and hope to have a fix asap

**Comment by zimme** [comment]
Please try version `1.0.6-alpha.1` to verify the fix.

**Comment by zimme** [comment]
So it looks like this fix just solved my part of the problem, I've found the underlying problem with `matb33:collection-hooks` and I'll try and put together a PR for that this weekend.
