### ISSUE TITLE
find by _id will bypass softremove and return the removed document

### ISSUE THREAD

**Issue by WayneUong** [zimme/meteor-collection-softremovable#28]
![screen shot 2017-02-10 at 3 33 46 pm](https://cloud.githubusercontent.com/assets/8436742/22848040/6c0b2256-efa6-11e6-90b4-5a2c4fedaa3d.png)

**Comment by zimme** [comment]
Yes, this is intended behaviour.

This is however changed in `1.0.6-alpha.2`.

```sh
meteor add zimme:collection-softremove@1.0.6-alpha.2
```

**Comment by zimme** [comment]
I'm working on a new version of this package that will be released under [collectionbehaviours:softremove](/meteor-collectionbehaviours/softremove) which will have this new behaviour as default.
