### ISSUE TITLE
Check compatibility with autoform 5

### ISSUE THREAD

**Issue by zimme** [zimme/meteor-collection-softremovable#3]
Investigate `aldeed:autoform` 5 compatibility

**Comment by appshore** [comment]
Got same issue https://github.com/zimme/meteor-collection-timestampable/issues/3

meteor add zimme:collection-softremovable
 => Errors while adding packages:             
                                              
While selecting package versions:
error: conflict: constraint aldeed:autoform@4.0.0 is not satisfied by 5.0.2.
Constraints on aldeed:autoform come from:
<top level>
zimme:collection-softremovable@1.0.0

**Comment by zimme** [comment]
I've published `1.0.4-rc.0`

Please try and manually update with `meteor update zimme:collection-softremovable@1.0.4-rc.0`

Please get back to me with the results. Once I have confirmation it works as expected I'll release 1.0.4.
I don't have time to test this myself until the weekend as I'm getting settled at the new employer.

**Comment by zimme** [comment]
Closed by 207a749808712e519858d083e2f3e47e6273f020. Please report issues I've missed any.
