### ISSUE TITLE
Check on update logic

### ISSUE THREAD

**Issue by zimme** [zimme/meteor-collection-softremovable#6]
Make sure updates with "general" selectors don't change soft-removed documents unless `{removed: true}` is in the selector or provided as an option

**Comment by zimme** [comment]
Works as expected. Add test for this when tests are added.

**Comment by lmachens** [comment]
I just tested the update logic. It looks like that with .update() all documents are updated. Even the removed ones.

Test it (Client side):

```
Collection = new Mongo.Collection(null);
Collection.attachBehaviour('softRemovable');
const id = Collection.insert({a: 1});
Collection.softRemove(id);
Collection.update({a: 1}, {$set: {b: 2}});
Collection.findOne(id);
```

For me this is not an intended behaivor.

**Comment by zimme** [comment]
I believe `update` have the same logic as find for when you use specific ids.

I'll change this with the other PR and I can release a pre release version which will have to be manually upgraded too.

**Comment by lmachens** [comment]
Ok thx. But the update query doesn't contain an _id here.
I think in @collection.before.update something like that is missing:
```
if not $unset[removed] and doc[removed]?
  return false
```
So it won't update a document which is removed unless you restore it.

**Comment by zimme** [comment]
The thing is that an update always trigger find, as update uses find to find the document which to update.

So by changing the behaviour of the find hooks the other hooks should get the new behaviour too.
