### ISSUE TITLE
Allow softRemove to be used inside a method stub

### ISSUE THREAD

**Issue by lorensr** [zimme/meteor-collection-softremovable#8]
I have deny rules blocking the client from changing the DB. When I call a method that has a `Items.remove`, the method executes a stub/simulation on the client. In the stub, the `remove` is run against the local `Items` collection. However, when I try `Items.softRemove`, I get this error on the client:

Exception while simulating the effect of invoking 'method_foo'
Meteor.makeErrorType.errorClass {error: 403, reason: "Not permitted. Untrusted code may only softRemove documents by ID.", details: undefined, message: "Not permitted. Untrusted code may only softRemove documents by ID. [403]", errorType: "Meteor.Error"…} Error: Not permitted. Untrusted code may only softRemove documents by ID. [403]

I think it would be better for this package to follow the Meteor convention of allowing updates to the local collection in method stubs. Perhaps it can check `this.isSimulation` and operate on `Items._collection`

**Comment by zimme** [comment]
I'll try and have a look at this as soon as possible. I've tried to reproduce how the regular `.remove()` function works but I might have missed something.

**Comment by zimme** [comment]
I haven't had time to look at this yet. If you need this fast, I will gladly accept a PR otherwise I'll get to it once I have the time.

**Comment by lorensr** [comment]
No worries, and no rush, thanks

**Comment by lorensr** [comment]
🙏😃

**Comment by zimme** [comment]
Published `1.0.5-rc.1` please try it out and once all changes have been tested I'll publish `1.0.5`.

**Comment by lorensr** [comment]
Still getting the error on `1.0.5-rc.1`:

![image](https://cloud.githubusercontent.com/assets/251288/9429564/7c69f380-49a2-11e5-80fc-f95a8a42d82e.png)

**Comment by zimme** [comment]
Hopefully `1.0.5-rc.2` got the if statement correct :smile:

**Comment by lorensr** [comment]
Sorry, still get error :)

The `set_friend` method is defined in `lib/` and contains `Friends.softRemove {from: ..., to: ...}`.

```
$ meteor list | grep soft
zimme:collection-softremovable                1.0.5-rc.2  Add soft remove to ...
```

**Comment by zimme** [comment]
Yeah, I've made the mistake of using `Meteor.isSimulation` instead of `this.isSimulation`.

I've setup a test method now and are working to fix this for real this time :stuck_out_tongue:

**Comment by zimme** [comment]
Oh, I just realized that I haven't implemented `softRemove` and `restore` as meteor methods the same way `insert`/`update`/`remove` are. So `this.isSimulation` isn't available for me to use.

I've been thinking about implementing my functions the same way for a while but forgot about it.

I'll try and get this done tonight, but I have my suspicions it will take longer.

**Comment by zimme** [comment]
This should be fixed with `1.0.5-rc.3`, I realized that I could just leverage the checks in `update` and re-throw the error with just a change to the method name in the message.

**Comment by lorensr** [comment]
Works, thanks.

**Comment by zimme** [comment]
:+1:

**Comment by zimme** [comment]
`1.0.5` published.
